### ISSUE TITLE
How to use your plugin correctly in general?

### ISSUE THREAD

**Issue by ga-al** [gabrielrbarbosa/figma-to-bootstrap-plugin#2]
The plugin does not copy the element code correctly

We have a ready-made bootstrap template for figma https://www.figma.com/file/EQDxOPS0FcrzCl8dKbLtWF/free-sketch-bootstrap5-ui-kit?type=design&node-id=0%3A1635&mode=design&t=gRq3wzcyW08DfGlZ-1

In it, all elements are called bootstrap classes, for example:

Components page, 05) Buttins, btn/btn-primary

We use your plugin, the Copy layer code button and get the following code:
<div id="component" class="container-fluid py-3">
     <div class="justify-content-center align-items-center">
         <div class="position-relative col-12 row d-flex">
             <div class="position-relative col-12">
                 <div class="left-0 top-0 position-absolute bg-primary rounded-1 col-12">
                 </div>
             </div>
             <div class="opacity-10 rounded-1 col-12">
             </div>
             <p class="text-center text-white fs-6 fw-medium font-family-HelveticaNeue col-8 m-0 px-3 py-2">
             Primary
             </p>
         </div>
     </div>
</div>

And we expect to receive something similar to:

<button type="button" class="btn btn-primary">Primary</button>

How to use your plugin correctly in general?
We are ready to work with this bootstrap template in Figma.

Is it possible to disable the positioning of elements relative to the page? So that you can take only part of the code, and not the entire page?

How do you expect an accordion block, for example, to be transferred to layout?

Or even a whole page?

Figma (https://www.figma.com/file/EQDxOPS0FcrzCl8dKbLtWF/free-sketch-bootstrap5-ui-kit?type=design&node-id=0%3A1635&mode=design&t=gRq3wzcyW08DfGlZ-1)
free-sketch-bootstrap5-ui-kit
Created with Figma

**Comment by gabrielrbarbosa** [comment]
Yes you can select only the layers you want to export or the whole page.
Colors are expected to get the approximate color from boostrap defaults if it's not working maybe it's a bug.

If you used Auto Layout in figma it will generate bootstrap rows and columns based on the parent layer you selected, otherwise it will generate HTML with position absolute.

I could made a setting to copy the layer code as a class name for that component but it may polute the generated HTML.
Other components are in the todo list but it's an extensive work so feel free to open PR if you want :)
